version: '3.4'

services:
  ocelotapi:
    image: ${DOCKER_REGISTRY-}ocelotapi
    build:
      context: .
      dockerfile: src/ApiGateways/OcelotAPI/Dockerfile

  authapi:
    image: ${DOCKER_REGISTRY-}authapi
    build:
      context: .
      dockerfile: src/Services/Auth/AuthAPI/Dockerfile

  movieapi:
    image: ${DOCKER_REGISTRY-}movieapi
    build:
      context: .
      dockerfile: src/Services/Movie/MovieAPI/Dockerfile
      